version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: client_web_prod:latest
    container_name: client_prod
    ports:
      - "3000:80"
    restart: unless-stopped
