version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: client_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
