apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - name: lms-backend 
          image: devesh121/lms-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-Secrets
          resources:
            requests:
              cpu: "200m"   # 200 millicpu = 0.2 cpu
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"

    