apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: lms-frontend
          image: devesh121/lms-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:     # for pod auto-scaling with HPA
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"   # 250 millicpu = 0.25 cpu
              memory: "256Mi"   # 256 Mi = 0.25 Gi or 256 MiB
